# Generated by Django 3.1.8 on 2021-04-18 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AMC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "AMC",
                "verbose_name_plural": "AMCs",
            },
        ),
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=128, unique=True)),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                ("kyc", models.BooleanField(default=False)),
                ("pan_kyc", models.BooleanField(default=False)),
                (
                    "amc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mutualfunds.amc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FolioScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valuation", models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ("xirr", models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ("valuation_date", models.DateField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="mutualfunds.folio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("DEBT", "Debt"),
                            ("HYBRID", "Hybrid"),
                            ("OTHER", "Other"),
                        ],
                        default="EQUITY",
                        max_length=8,
                    ),
                ),
                ("subtype", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "FundCategory",
                "verbose_name_plural": "Fund Categories",
            },
        ),
        migrations.CreateModel(
            name="FundScheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sid", models.IntegerField(help_text="Source ID for scheme", unique=True)),
                ("name", models.CharField(max_length=512, db_index=True)),
                ("rta", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("DIRECT", "Direct")],
                        default="REGULAR",
                        max_length=8,
                    ),
                ),
                ("rta_code", models.CharField(max_length=32)),
                ("amc_code", models.CharField(db_index=True, max_length=32)),
                ("amfi_code", models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ("isin", models.CharField(db_index=True, max_length=16)),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "amc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funds",
                        to="mutualfunds.amc",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funds",
                        to="mutualfunds.fundcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Scheme",
                "verbose_name_plural": "Fund Schemes",
                "indexes" : [
                    models.Index(fields=["amc_id", "rta_code"], name="idx_rta_code_amc_id"),
                    models.Index(fields=["rta", "rta_code"], name="idx_rta_code_rta"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("Buy", "Buy"),
                            ("Reinvest", "Reinvest"),
                            ("Redeem", "Redeem"),
                            ("Switch", "Switch"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        blank=True,
                        help_text="Order type as classified by casparser",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("nav", models.DecimalField(decimal_places=4, max_digits=15)),
                ("units", models.DecimalField(decimal_places=3, max_digits=20)),
                ("balance", models.DecimalField(decimal_places=3, max_digits=40)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="mutualfunds.folioscheme",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
        migrations.AddField(
            model_name="folioscheme",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schemes",
                to="mutualfunds.fundscheme",
            ),
        ),
        migrations.AddField(
            model_name="folio",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folios",
                to="mutualfunds.portfolio",
            ),
        ),
        migrations.CreateModel(
            name="SchemeValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("invested", models.DecimalField(decimal_places=2, max_digits=30)),
                ("value", models.DecimalField(decimal_places=2, max_digits=30)),
                ("avg_nav", models.DecimalField(decimal_places=10, default=0.0, max_digits=30)),
                ("nav", models.DecimalField(decimal_places=4, max_digits=15)),
                ("balance", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="mutualfunds.folioscheme",
                    ),
                ),
            ],
            options={
                "get_latest_by": ("date",),
                "unique_together": {("scheme_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("invested", models.DecimalField(decimal_places=2, max_digits=30)),
                ("value", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "xirr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "live_xirr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="mutualfunds.portfolio",
                    ),
                ),
            ],
            options={
                "get_latest_by": ("date",),
                "unique_together": {("portfolio_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="NAVHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("nav", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mutualfunds.fundscheme"
                    ),
                ),
            ],
            options={
                "unique_together": {("scheme_id", "date")},
            },
        ),
        migrations.CreateModel(
            name="FolioValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("invested", models.DecimalField(decimal_places=2, max_digits=30)),
                ("value", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="mutualfunds.folio",
                    ),
                ),
            ],
            options={
                "get_latest_by": ("date",),
                "unique_together": {("folio_id", "date")},
            },
        ),
    ]
