# Generated by Django 3.1.7 on 2021-04-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutualfunds", "0002_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="sub_type",
            field=models.CharField(
                blank=True,
                help_text="Order type as classified by casparser",
                max_length=32,
                null=True,
            ),
        ),
    ]
