# Generated by Django 3.1.7 on 2021-04-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mutualfunds", "0003_transaction_sub_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="avg_nav",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="invested",
        ),
    ]
