# Generated by Django 3.1.7 on 2021-04-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mutualfunds", "0004_auto_20210404_1847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foliovalue",
            options={"get_latest_by": ("date",)},
        ),
        migrations.AlterModelOptions(
            name="portfoliovalue",
            options={"get_latest_by": ("date",)},
        ),
        migrations.AlterModelOptions(
            name="schemevalue",
            options={"get_latest_by": ("date",)},
        ),
        migrations.AlterField(
            model_name="folioscheme",
            name="folio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemes",
                to="mutualfunds.folio",
            ),
        ),
    ]
