# Generated by Django 3.1.7 on 2021-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutualfunds", "0005_auto_20210406_2353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folioscheme",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="folioscheme",
            name="balance_date",
        ),
        migrations.AddField(
            model_name="folioscheme",
            name="valuation",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="folioscheme",
            name="valuation_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="folioscheme",
            name="xirr",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="portfoliovalue",
            name="live_xirr",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="portfoliovalue",
            name="xirr",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
