# Generated by Django 3.1.2 on 2020-10-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("folioman", "0001_initial"),
    ]

    operations = []
