# Generated by Django 3.1.2 on 2020-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioman", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
