# Generated by Django 3.1.3 on 2020-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioman", "0002_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="avg_nav",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="invested",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
