# Generated by Django 5.2.14 on 2026-06-01 12:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AMC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "verbose_name": "AMC",
                "verbose_name_plural": "AMCs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.TextField(unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("tax_pack", "Tax Pack"), ("pm_pro", "PM Pro")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("licensee", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(default="INR", max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=18)),
                ("source", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "verbose_name": "FX rate",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_currency", "quote_currency", "date"),
                        name="uniq_fxrate_pair_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("is_huf", models.BooleanField(default=False)),
                ("relation", models.CharField(blank=True, default="", max_length=20)),
                ("pan_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "pan_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investors",
                        to="folioman_app.family",
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("cas", "CAS PDF"), ("csv", "CSV"), ("manual", "Manual entry")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("completed_with_warnings", "Completed with warnings"),
                            ("needs_confirmation", "Needs confirmation"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("source_ref", models.CharField(blank=True, default="", max_length=128)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="folioman_app.investor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folio_type",
                    models.CharField(choices=[("mf", "Mf"), ("demat", "Demat")], max_length=10),
                ),
                ("number", models.CharField(max_length=64)),
                ("broker", models.CharField(blank=True, default="", max_length=64)),
                ("amc_code", models.CharField(blank=True, default="", max_length=32)),
                ("pan_kyc", models.BooleanField(default=False)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folios",
                        to="folioman_app.investor",
                    ),
                ),
            ],
            options={
                "ordering": ["investor", "number"],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("mf", "Mf"),
                            ("equity", "Equity"),
                            ("etf", "Etf"),
                            ("bond", "Bond"),
                            ("fd", "Fd"),
                            ("crypto", "Crypto"),
                            ("foreign_equity", "Foreign Equity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("isin", models.CharField(blank=True, db_index=True, default="", max_length=12)),
                ("symbol", models.CharField(blank=True, default="", max_length=32)),
                ("exchange", models.CharField(blank=True, default="", max_length=16)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "amfi_code",
                    models.CharField(blank=True, db_index=True, default="", max_length=16),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "amc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="securities",
                        to="folioman_app.amc",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "securities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NAVHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("nav", models.DecimalField(decimal_places=6, max_digits=20)),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_history",
                        to="folioman_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "NAV history point",
                "verbose_name_plural": "NAV history",
                "ordering": ["security", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("as_of_date", models.DateField()),
                ("units", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "value_observed",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "avg_cost_observed",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ecas", "Ecas"),
                            ("manual", "Manual"),
                            ("cas-pdf", "Cas Pdf"),
                            ("ledger", "Ledger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, default="", max_length=128)),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="holdings",
                        to="folioman_app.folio",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="folioman_app.investor",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="folioman_app.security",
                    ),
                ),
            ],
            options={
                "ordering": ["investor", "security", "-as_of_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIntegrityStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("full_history", "Full History"),
                            ("snapshot_only", "Snapshot Only"),
                            ("reconciled", "Reconciled"),
                            ("mismatch", "Mismatch"),
                            ("user_acknowledged", "User Acknowledged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tax_safe", models.BooleanField(default=False)),
                (
                    "units_from_transactions",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                (
                    "units_from_holdings",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
                ),
                ("issues", models.JSONField(blank=True, default=list)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_statuses",
                        to="folioman_app.folio",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_statuses",
                        to="folioman_app.investor",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_statuses",
                        to="folioman_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "security integrity status",
                "verbose_name_plural": "security integrity statuses",
                "ordering": ["investor", "security", "folio"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("dividend", "Dividend"),
                            ("bonus", "Bonus"),
                            ("split", "Split"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                        ],
                        max_length=16,
                    ),
                ),
                ("units", models.DecimalField(decimal_places=8, max_digits=24)),
                ("nav_or_price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "fx_rate_to_inr",
                    models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=18),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "stamp_duty",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "brokerage",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cas-pdf", "Cas Pdf"),
                            ("manual", "Manual"),
                            ("csv-import", "Csv Import"),
                            ("corporate-action", "Corporate Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, default="", max_length=128)),
                ("narration", models.TextField(blank=True, default="")),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="folioman_app.folio",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="folioman_app.investor",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="folioman_app.security",
                    ),
                ),
            ],
            options={
                "ordering": ["investor", "date", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="family",
            constraint=models.UniqueConstraint(
                fields=("owned_by", "name"), name="uniq_family_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="investor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pan_hash", ""), _negated=True),
                fields=("owned_by", "pan_hash"),
                name="uniq_investor_pan",
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["investor", "status"], name="idx_importjob_inv_status"),
        ),
        migrations.AddConstraint(
            model_name="folio",
            constraint=models.UniqueConstraint(
                fields=("investor", "number", "amc_code"), name="uniq_folio_investor_number_amc"
            ),
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isin", ""), _negated=True),
                fields=("isin",),
                name="uniq_security_isin",
            ),
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.UniqueConstraint(
                condition=models.Q(("amfi_code", ""), _negated=True),
                fields=("amfi_code",),
                name="uniq_security_amfi_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="navhistory",
            constraint=models.UniqueConstraint(
                fields=("security", "date"), name="uniq_nav_security_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.UniqueConstraint(
                fields=("investor", "security", "folio", "as_of_date", "source"),
                name="uniq_holding_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("folio__isnull", True)),
                fields=("investor", "security", "as_of_date", "source"),
                name="uniq_holding_snapshot_no_folio",
            ),
        ),
        migrations.AddIndex(
            model_name="securityintegritystatus",
            index=models.Index(fields=["investor", "tax_safe"], name="idx_integrity_inv_taxsafe"),
        ),
        migrations.AddConstraint(
            model_name="securityintegritystatus",
            constraint=models.UniqueConstraint(
                fields=("investor", "security", "folio"),
                name="uniq_integrity_investor_security_folio",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["investor", "security", "date"], name="idx_txn_inv_sec_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key", ""), _negated=True),
                fields=("investor", "dedup_key"),
                name="uniq_txn_investor_dedup",
            ),
        ),
    ]
