# Generated by Django 5.2.14 on 2026-06-02 15:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='valuation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investor',
            name='valuation_computed_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='valuation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investor',
            name='valuation_next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='valuation_recompute_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='valuation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('computing', 'Computing'), ('ready', 'Ready'), ('error', 'Error')], default='ready', max_length=10),
        ),
        migrations.CreateModel(
            name='InvestorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('invested_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('value_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('is_provisional', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_values', to='folioman_app.investor')),
            ],
            options={
                'ordering': ['investor', 'date'],
                'indexes': [models.Index(fields=['investor', 'date'], name='idx_investor_value_date')],
                'constraints': [models.UniqueConstraint(fields=('investor', 'date'), name='uniq_investor_value_date')],
            },
        ),
    ]
