# Generated by Django 5.2.14 on 2026-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0002_investor_valuation_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityintegritystatus',
            name='ledger_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityintegritystatus',
            name='snapshot_as_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
