# Generated by Django 5.2.14 on 2026-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0003_securityintegritystatus_ledger_through_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='nav_feed_closed',
            field=models.BooleanField(default=False),
        ),
    ]
