# Generated by Django 5.2.14 on 2026-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0004_security_nav_feed_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost_basis_complete',
            field=models.BooleanField(default=True),
        ),
    ]
