# Generated by Django 5.2.14 on 2026-06-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0005_transaction_cost_basis_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_units', models.DecimalField(decimal_places=8, max_digits=24)),
                ('closing_units', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('statement_from', models.DateField(blank=True, null=True)),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_blocks', to='folioman_app.folio')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_blocks', to='folioman_app.investor')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_blocks', to='folioman_app.security')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor', 'security', 'folio'), name='uniq_partialblock_inv_sec_folio')],
            },
        ),
    ]
