# Generated by Django 5.2.14 on 2026-06-12 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0006_partialblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportQuarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('security_name', models.CharField(blank=True, default='', max_length=255)),
                ('isin', models.CharField(blank=True, default='', max_length=20)),
                ('folio_number', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine', to='folioman_app.importjob')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_quarantine', to='folioman_app.investor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor', 'resolved'], name='idx_quarantine_inv_resolved')],
            },
        ),
    ]
