# Generated by Django 5.2.15 on 2026-06-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folioman_app", "0007_importquarantine"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateActionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isin", models.CharField(blank=True, db_index=True, default="", max_length=12)),
                ("symbol", models.CharField(blank=True, default="", max_length=32)),
                ("series", models.CharField(blank=True, default="", max_length=8)),
                ("exchange", models.CharField(blank=True, default="", max_length=8)),
                ("ex_date", models.DateField()),
                ("record_date", models.DateField(blank=True, null=True)),
                ("subject", models.TextField()),
                ("parsed_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "unit_multiplier",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
                ),
                ("parsed", models.JSONField(blank=True, default=dict)),
                ("needs_review", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, default="", max_length=8)),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_actions",
                        to="folioman_app.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "corporate action reference",
                "verbose_name_plural": "corporate action references",
                "ordering": ["isin", "-ex_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("isin", "ex_date", "subject", "exchange"),
                        condition=models.Q(("isin", ""), _negated=True),
                        name="uniq_corp_action_isin_ex_subject_exch",
                    ),
                    models.UniqueConstraint(
                        fields=("symbol", "ex_date", "subject", "exchange"),
                        condition=models.Q(("isin", "")),
                        name="uniq_corp_action_sym_ex_subject_exch",
                    ),
                ],
            },
        ),
    ]
