# Generated by Django 5.2.15 on 2026-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0008_corporate_action_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True),
        ),
    ]
