# Generated by Django 5.2.15 on 2026-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0009_transaction_cost_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='corporate_actions_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
