# Generated by Django 5.2.15 on 2026-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0011_purge_misfiled_corporate_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('bonus', 'Bonus'), ('split', 'Split'), ('merger', 'Merger'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=16),
        ),
    ]
