# Generated by Django 5.2.15 on 2026-06-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioman_app', '0012_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=32)),
                ('ex_date', models.DateField()),
                ('unit_multiplier', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('bonus_ratio_a', models.IntegerField(blank=True, null=True)),
                ('bonus_ratio_b', models.IntegerField(blank=True, null=True)),
                ('merger_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('source_ref', models.CharField(blank=True, default='', max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('counterparty_security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='folioman_app.security')),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_corporate_actions', to='folioman_app.folio')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_corporate_actions', to='folioman_app.investor')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_corporate_actions', to='folioman_app.security')),
            ],
            options={
                'ordering': ['investor', 'ex_date', 'id'],
                'indexes': [models.Index(fields=['investor', 'security', 'ex_date'], name='idx_applied_ca_inv_sec_date')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('investor', 'folio', 'security', 'source_ref'), name='uniq_applied_ca_investor_folio_sec_ref')],
            },
        ),
    ]
