/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain Token
         * @description Exchange username + password for an access + refresh token pair.
         */
        post: operations["folioman_app_api_tokens_obtain_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Mint a fresh access token from a still-valid refresh token.
         */
        post: operations["folioman_app_api_tokens_refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Families */
        get: operations["folioman_app_api_families_list_families"];
        put?: never;
        /** Create Family */
        post: operations["folioman_app_api_families_create_family"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Family */
        get: operations["folioman_app_api_families_get_family"];
        put?: never;
        post?: never;
        /** Delete Family */
        delete: operations["folioman_app_api_families_delete_family"];
        options?: never;
        head?: never;
        /** Update Family */
        patch: operations["folioman_app_api_families_update_family"];
        trace?: never;
    };
    "/api/families/{family_id}/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Family Aggregate */
        get: operations["folioman_app_api_families_family_aggregate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}/valuation-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Family Valuation Status
         * @description Combined readiness — ready only when every member's day-wise valuation is.
         */
        get: operations["folioman_app_api_families_family_valuation_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}/value-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Family Value Series Endpoint
         * @description Family-wide net-worth-over-time, aggregated across the family's investors.
         */
        get: operations["folioman_app_api_families_family_value_series_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/cas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Cas
         * @description Import a CAS, resolving (or creating) its investor by PAN.
         *
         *     Auto-detects MF CAS vs NSDL/CDSL eCAS. An eCAS that would *remove* securities
         *     returns the job at status ``needs_confirmation`` with ``result.removals`` and
         *     persists nothing — resubmit with ``confirm=true`` to apply. A PAN-less
         *     statement is rejected (422); nothing is created.
         */
        post: operations["folioman_app_api_imports_import_cas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/cas/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Cas
         * @description Parse a CAS and report whose it is + what's inside — persisting nothing.
         *
         *     Returns the owner's name + masked PAN (and an existing-investor match for
         *     'attach' vs 'create'), plus content stats (period, counts, full-history vs
         *     snapshot) so the UI can flag a Summary/partial statement before import.
         */
        post: operations["folioman_app_api_imports_preview_cas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investors */
        get: operations["folioman_app_api_investors_list_investors"];
        put?: never;
        /** Create Investor */
        post: operations["folioman_app_api_investors_create_investor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roster Aggregate
         * @description Advisor-wide roster header. Declared before ``/{investor_id}`` so the literal
         *     path wins over the int param route.
         */
        get: operations["folioman_app_api_investors_roster_aggregate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investor */
        get: operations["folioman_app_api_investors_get_investor"];
        put?: never;
        post?: never;
        /** Delete Investor */
        delete: operations["folioman_app_api_investors_delete_investor"];
        options?: never;
        head?: never;
        /** Update Investor */
        patch: operations["folioman_app_api_investors_update_investor"];
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/capital-gains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capital Gains
         * @description Realised capital gains for one FY: STCG/LTCG totals + per-disposal rows
         *     (equity-MF only in v1). A read view to review — not a filed return.
         */
        get: operations["folioman_app_api_exports_capital_gains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Holdings
         * @description Current holdings + valuation as a downloadable CSV (free tier).
         */
        get: operations["folioman_app_api_exports_export_holdings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/schedule-112a": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule 112A
         * @description A capital-gains worksheet (Schedule 112A shape) to review with your CA —
         *     free, and only built from tax-ready folios.
         */
        post: operations["folioman_app_api_exports_schedule_112a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Full transaction ledger as a CSV in the import format (round-trippable).
         */
        get: operations["folioman_app_api_exports_export_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/folios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folios */
        get: operations["folioman_app_api_investors_list_folios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/holdings/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scheme Detail
         * @description One scheme's detail: identity, metrics, integrity, NAV history, ledger.
         *     404 if the investor has never held or transacted this security.
         */
        get: operations["folioman_app_api_investors_scheme_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Import Jobs */
        get: operations["folioman_app_api_imports_list_import_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv */
        post: operations["folioman_app_api_imports_import_csv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Job */
        get: operations["folioman_app_api_imports_get_import_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Integrity */
        get: operations["folioman_app_api_integrity_list_integrity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["folioman_app_api_integrity_recompute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity/{security_id}/{folio_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["folioman_app_api_integrity_acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity/{security_id}/{folio_id}/unacknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unacknowledge
         * @description Undo an acknowledgement: the row reverts to its real status (an unresolved
         *     gap reappears as a mismatch). Lets the user take back a mis-click.
         */
        post: operations["folioman_app_api_integrity_unacknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investor Summary
         * @description Roster headline numbers: current INR value, tax-ready vs total holdings,
         *     items needing attention, and the last successful import date.
         */
        get: operations["folioman_app_api_investors_investor_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["folioman_app_api_investors_list_transactions"];
        put?: never;
        /**
         * Create Transaction
         * @description Manually add one transaction (security identified inline, upserted).
         *
         *     Gated off by default in the first release (CAS/eCAS imports only). Flip
         *     ``FOLIOMAN_MANUAL_TXNS=1`` to enable; the logic below is unchanged.
         */
        post: operations["folioman_app_api_investors_create_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/valuation-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investor Valuation Status
         * @description Whether the day-wise valuation is ready (chart gate) or still computing —
         *     the dashboard polls this and shows a placeholder + provisional value meanwhile.
         */
        get: operations["folioman_app_api_investors_investor_valuation_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/value-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investor Value Series
         * @description Net-worth-over-time, reconstructed from the ledger + NAV history. The final
         *     point matches the point-in-time ``/summary`` value for the same ``to`` date.
         */
        get: operations["folioman_app_api_investors_investor_value_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Meta */
        get: operations["folioman_app_api_meta_app_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessOut */
        AccessOut: {
            /** Access */
            access: string;
        };
        /**
         * AllocationBucket
         * @description One slice of a sub-asset-class allocation breakdown (by AMC, by category).
         */
        AllocationBucket: {
            /** Label */
            label: string;
            /** Value Inr */
            value_inr: string;
        };
        /** AppMetaOut */
        AppMetaOut: {
            /** Data Location */
            data_location: string;
            /** Storage */
            storage: string;
            /** Version */
            version: string;
        };
        /** AssetMixRow */
        AssetMixRow: {
            /** Security Type */
            security_type: string;
            /** Value Inr */
            value_inr: string;
        };
        /**
         * CapitalGainRow
         * @description One realised disposal (FIFO lot) in the capital-gains view.
         */
        CapitalGainRow: {
            /**
             * Acquired On
             * Format: date
             */
            acquired_on: string;
            /** Cost */
            cost: string;
            /** Gain */
            gain: string;
            /**
             * Grandfathering Unavailable
             * @default false
             */
            grandfathering_unavailable: boolean;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Sale Value */
            sale_value: string;
            /** Security Id */
            security_id: number | null;
            /**
             * Sold On
             * Format: date
             */
            sold_on: string;
            /** Term */
            term: string;
            /** Units */
            units: string;
        };
        /**
         * CapitalGainsOut
         * @description Realised capital gains for one FY — STCG/LTCG split, equity-MF only in v1.
         */
        CapitalGainsOut: {
            /**
             * Disclaimer
             * @default Heads up — this isn't tax advice. folioman builds a capital-gains worksheet from the transactions you import, so you and your CA have a starting point. It doesn't file anything, it's no substitute for a Chartered Accountant, and we can't promise the numbers are right or complete — a misparsed or incomplete statement can throw them off. Always check every figure with a qualified CA before you file. Provided as-is, no warranty; we're not liable for any filing, penalty, or loss that comes from using it.
             */
            disclaimer: string;
            /** Fy */
            fy: string;
            /** Ltcg Total */
            ltcg_total: string;
            /** Rows */
            rows?: components["schemas"]["CapitalGainRow"][];
            /** Stcg Total */
            stcg_total: string;
        };
        /**
         * CasPreviewOut
         * @description Owner identity parsed from an uploaded CAS, before anything is persisted.
         *
         *     Lets the UI confirm who the statement belongs to (and whether it matches an
         *     existing investor) before the import creates or attaches. Only a *masked* PAN
         *     is returned — the full PAN is never sent back to the client.
         */
        CasPreviewOut: {
            /** From Date */
            from_date?: string | null;
            /**
             * Full History
             * @default false
             */
            full_history: boolean;
            /**
             * Holding Count
             * @default 0
             */
            holding_count: number;
            /** Investor Email */
            investor_email: string;
            /** Investor Name */
            investor_name: string;
            /** Kind */
            kind: string;
            /** Match Investor Id */
            match_investor_id?: number | null;
            /** Match Investor Name */
            match_investor_name?: string | null;
            /** Pan Masked */
            pan_masked: string;
            /**
             * Scheme Count
             * @default 0
             */
            scheme_count: number;
            /**
             * Snapshot Scheme Count
             * @default 0
             */
            snapshot_scheme_count: number;
            /** To Date */
            to_date?: string | null;
            /**
             * Transaction Count
             * @default 0
             */
            transaction_count: number;
        };
        /** FamilyAggregateOut */
        FamilyAggregateOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Mix */
            asset_mix: components["schemas"]["AssetMixRow"][];
            /** Day Change Inr */
            day_change_inr?: string | null;
            /** Family Id */
            family_id: number;
            /**
             * Folio Count
             * @default 0
             */
            folio_count: number;
            /**
             * Integrity Unit Count
             * @default 0
             */
            integrity_unit_count: number;
            /** Investor Count */
            investor_count: number;
            /**
             * Needs Attention Count
             * @default 0
             */
            needs_attention_count: number;
            /** Stale Count */
            stale_count: number;
            /**
             * Tax Ready Count
             * @default 0
             */
            tax_ready_count: number;
            /** Top Holdings */
            top_holdings: components["schemas"]["HoldingValueRow"][];
            /** Total Inr */
            total_inr: string;
            /** Xirr */
            xirr?: number | null;
        };
        /** FamilyDetailOut */
        FamilyDetailOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Investor Count */
            investor_count: number;
            /** Investors */
            investors: components["schemas"]["InvestorOut"][];
            /** Name */
            name: string;
        };
        /** FamilyIn */
        FamilyIn: {
            /** Name */
            name: string;
        };
        /** FamilyOut */
        FamilyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Investor Count */
            investor_count: number;
            /** Name */
            name: string;
        };
        /** FolioOut */
        FolioOut: {
            /** Amc Code */
            amc_code: string;
            /** Broker */
            broker: string;
            /** Folio Type */
            folio_type: string;
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Pan Kyc */
            pan_kyc: boolean;
        };
        /** FolioRef */
        FolioRef: {
            /** Broker */
            broker: string;
            /** Folio Type */
            folio_type: string;
            /** Id */
            id: number;
            /** Number */
            number: string;
        };
        /** HoldingValueRow */
        HoldingValueRow: {
            /**
             * Amc
             * @default
             */
            amc: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Day Change Inr */
            day_change_inr?: string | null;
            /** Day Change Pct */
            day_change_pct?: number | null;
            /** Invested Inr */
            invested_inr?: string | null;
            /** Name */
            name: string;
            /** Return Pct */
            return_pct?: number | null;
            /** Security Id */
            security_id: number;
            /** Security Type */
            security_type: string;
            /** Units */
            units: string;
            /** Value Inr */
            value_inr: string | null;
            /** Xirr */
            xirr?: number | null;
        };
        /** ImportJobOut */
        ImportJobOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string;
            /** Filename */
            filename: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Investor Id */
            investor_id: number;
            /** Kind */
            kind: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Source Ref */
            source_ref: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** IntegrityStatusOut */
        IntegrityStatusOut: {
            folio: components["schemas"]["FolioRef"];
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
            /** Last Reconciled At */
            last_reconciled_at: string | null;
            /** Ledger Through */
            ledger_through: string | null;
            security: components["schemas"]["SecurityRef"];
            /** Snapshot As Of */
            snapshot_as_of: string | null;
            /** Status */
            status: string;
            /** Tax Safe */
            tax_safe: boolean;
            /** Units From Holdings */
            units_from_holdings: string | null;
            /** Units From Transactions */
            units_from_transactions: string | null;
        };
        /** InvestorDetailOut */
        InvestorDetailOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Family Id */
            family_id: number | null;
            /** Has Pan */
            has_pan: boolean;
            /** Id */
            id: number;
            /** Is Huf */
            is_huf: boolean;
            /** Name */
            name: string;
            /** Pan Locked */
            pan_locked: boolean;
            /** Pan Masked */
            pan_masked: string;
            /** Relation */
            relation: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InvestorIn */
        InvestorIn: {
            /**
             * Email
             * @default
             */
            email: string;
            /** Family Id */
            family_id?: number | null;
            /** Name */
            name: string;
            /** Pan */
            pan?: string | null;
        };
        /** InvestorOut */
        InvestorOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Family Id */
            family_id: number | null;
            /** Has Pan */
            has_pan: boolean;
            /** Id */
            id: number;
            /** Is Huf */
            is_huf: boolean;
            /** Name */
            name: string;
            /** Pan Locked */
            pan_locked: boolean;
            /** Relation */
            relation: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InvestorRowOut
         * @description One roster-list row — the lean fields the Investors page shows, computed in
         *     the single bulk aggregate pass (no per-investor /summary fan-out).
         */
        InvestorRowOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Holdings Count */
            holdings_count: number;
            /** Integrity Unit Count */
            integrity_unit_count: number;
            /** Investor Id */
            investor_id: number;
            /**
             * Is Provisional
             * @default false
             */
            is_provisional: boolean;
            /** Last Import At */
            last_import_at?: string | null;
            /** Needs Attention Count */
            needs_attention_count: number;
            /** Snapshot Count */
            snapshot_count: number;
            /** Tax Ready Count */
            tax_ready_count: number;
            /** Total Inr */
            total_inr: string;
            /**
             * Unpriced Fund Count
             * @default 0
             */
            unpriced_fund_count: number;
        };
        /**
         * InvestorSummaryOut
         * @description Per-investor headline numbers for the roster row.
         */
        InvestorSummaryOut: {
            /** Amc Mix */
            amc_mix?: components["schemas"]["AllocationBucket"][];
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Mix */
            asset_mix?: components["schemas"]["AssetMixRow"][];
            /** Category Mix */
            category_mix?: components["schemas"]["AllocationBucket"][];
            /** Day Change Inr */
            day_change_inr?: string | null;
            /** Holdings */
            holdings?: components["schemas"]["HoldingValueRow"][];
            /** Holdings Count */
            holdings_count: number;
            /** Integrity Unit Count */
            integrity_unit_count: number;
            /** Investor Id */
            investor_id: number;
            /**
             * Is Provisional
             * @default false
             */
            is_provisional: boolean;
            /** Last Import At */
            last_import_at: string | null;
            /** Needs Attention Count */
            needs_attention_count: number;
            /** Snapshot Count */
            snapshot_count: number;
            /** Stale Count */
            stale_count: number;
            /** Tax Ready Count */
            tax_ready_count: number;
            /** Top Holdings */
            top_holdings?: components["schemas"]["HoldingValueRow"][];
            /** Total Inr */
            total_inr: string;
            /** Unpriced Fund Count */
            unpriced_fund_count: number;
            /** Xirr */
            xirr?: number | null;
        };
        /** InvestorUpdate */
        InvestorUpdate: {
            /** Email */
            email?: string | null;
            /** Family Id */
            family_id?: number | null;
            /** Name */
            name?: string | null;
            /** Pan */
            pan?: string | null;
        };
        /** NavPoint */
        NavPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Nav */
            nav: string;
        };
        /**
         * RosterAggregateOut
         * @description Advisor-wide roster header (net worth + counts + integrity roll-up) plus a
         *     lean per-investor row for the list — one request for the whole landing page.
         */
        RosterAggregateOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Family Count */
            family_count: number;
            /** Integrity Unit Count */
            integrity_unit_count: number;
            /** Investor Count */
            investor_count: number;
            /** Needs Attention Count */
            needs_attention_count: number;
            /** Rows */
            rows?: components["schemas"]["InvestorRowOut"][];
            /** Snapshot Count */
            snapshot_count: number;
            /** Tax Ready Count */
            tax_ready_count: number;
            /** Total Inr */
            total_inr: string;
        };
        /** Schedule112ARequest */
        Schedule112ARequest: {
            /**
             * Fy
             * @description India FY, e.g. 2024-25
             */
            fy: string;
            /**
             * Include Unreconciled
             * @default false
             */
            include_unreconciled: boolean;
        };
        /** Schedule112AResponse */
        Schedule112AResponse: {
            /** Columns */
            columns: string[];
            /**
             * Disclaimer
             * @default Heads up — this isn't tax advice. folioman builds a capital-gains worksheet from the transactions you import, so you and your CA have a starting point. It doesn't file anything, it's no substitute for a Chartered Accountant, and we can't promise the numbers are right or complete — a misparsed or incomplete statement can throw them off. Always check every figure with a qualified CA before you file. Provided as-is, no warranty; we're not liable for any filing, penalty, or loss that comes from using it.
             */
            disclaimer: string;
            /** Fy */
            fy: string;
            /** Include Unreconciled */
            include_unreconciled: boolean;
            /**
             * Is Draft
             * @default true
             */
            is_draft: boolean;
            /** Row Count */
            row_count: number;
            /** Rows */
            rows: {
                [key: string]: string;
            }[];
            /**
             * Title
             * @default Capital-gains worksheet (for review)
             */
            title: string;
        };
        /**
         * SchemeDetailOut
         * @description Everything one scheme page needs in a single call: identity, current
         *     metrics, integrity per folio, the NAV history series, and the ledger.
         */
        SchemeDetailOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Day Change Inr */
            day_change_inr: string | null;
            /** Day Change Pct */
            day_change_pct: number | null;
            /** Has Transactions */
            has_transactions: boolean;
            /** Integrity */
            integrity: components["schemas"]["IntegrityStatusOut"][];
            /** Invested Inr */
            invested_inr: string | null;
            /** Latest Nav */
            latest_nav: string | null;
            /** Latest Nav Date */
            latest_nav_date: string | null;
            /** Nav History */
            nav_history: components["schemas"]["NavPoint"][];
            /** Return Pct */
            return_pct: number | null;
            security: components["schemas"]["SchemeRef"];
            /** Transactions */
            transactions: components["schemas"]["TransactionOut"][];
            /** Units */
            units: string;
            /** Value Inr */
            value_inr: string | null;
            /** Xirr */
            xirr: number | null;
            /** Xirr Status */
            xirr_status: string;
        };
        /**
         * SchemeRef
         * @description Security identity for the scheme-detail header band.
         */
        SchemeRef: {
            /** Amc */
            amc?: string | null;
            /** Amfi Code */
            amfi_code: string;
            /** Category */
            category?: string | null;
            /** Id */
            id: number;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Security Type */
            security_type: string;
            /** Symbol */
            symbol: string;
        };
        /** SecurityRef */
        SecurityRef: {
            /** Id */
            id: number;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Security Type */
            security_type: string;
            /** Symbol */
            symbol: string;
        };
        /** TokenObtainIn */
        TokenObtainIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /** TokenRefreshIn */
        TokenRefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /**
         * TransactionIn
         * @description A single manually-entered transaction (security identified inline).
         */
        TransactionIn: {
            /**
             * Amfi Code
             * @default
             */
            amfi_code: string;
            /** Amount */
            amount?: number | string | null;
            /**
             * Broker
             * @default
             */
            broker: string;
            /**
             * Brokerage
             * @default 0
             */
            brokerage: number | string;
            /**
             * Coin Id
             * @default
             */
            coin_id: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Fees
             * @default 0
             */
            fees: number | string;
            /** Folio Number */
            folio_number: string;
            /**
             * Isin
             * @default
             */
            isin: string;
            /** Name */
            name: string;
            /**
             * Narration
             * @default
             */
            narration: string;
            /** Price */
            price: number | string;
            /**
             * Principal
             * @default
             */
            principal: string;
            /** Security Type */
            security_type: string;
            /**
             * Stamp Duty
             * @default 0
             */
            stamp_duty: number | string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Transaction Type */
            transaction_type: string;
            /** Units */
            units: number | string;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Amount */
            amount: string | null;
            /** Brokerage */
            brokerage: string;
            /** Currency */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fees */
            fees: string;
            /** Folio Id */
            folio_id: number | null;
            /** Id */
            id: number;
            /** Investor Id */
            investor_id: number;
            /** Narration */
            narration: string;
            /** Nav Or Price */
            nav_or_price: string;
            /** Security Id */
            security_id: number;
            /** Source */
            source: string;
            /** Stamp Duty */
            stamp_duty: string;
            /** Transaction Type */
            transaction_type: string;
            /** Units */
            units: string;
        };
        /**
         * ValuationStatusOut
         * @description Day-wise valuation readiness for an investor or family. The dashboard gates
         *     the net-worth chart on ``status == 'ready'`` and polls while it isn't; the
         *     headline numbers stay ungated (backed by the provisional value meanwhile).
         */
        ValuationStatusOut: {
            /** Computed Through */
            computed_through?: string | null;
            /** Family Id */
            family_id?: number | null;
            /** Investor Id */
            investor_id?: number | null;
            /**
             * Is Provisional
             * @default false
             */
            is_provisional: boolean;
            /** Recompute From */
            recompute_from?: string | null;
            /** Status */
            status: string;
        };
        /**
         * ValueSeriesOut
         * @description Reconstructed net-worth-over-time series for an investor or family.
         */
        ValueSeriesOut: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** Family Id */
            family_id?: number | null;
            /** Granularity */
            granularity: string;
            /** Investor Id */
            investor_id?: number | null;
            /** Points */
            points: components["schemas"]["ValueSeriesPoint"][];
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /**
         * ValueSeriesPoint
         * @description One sampled date in the net-worth time series.
         */
        ValueSeriesPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Invested Inr */
            invested_inr: string;
            /** Stale */
            stale: boolean;
            /** Value Inr */
            value_inr: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    folioman_app_api_tokens_obtain_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
        };
    };
    folioman_app_api_tokens_refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessOut"];
                };
            };
        };
    };
    folioman_app_api_families_list_families: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"][];
                };
            };
        };
    };
    folioman_app_api_families_create_family: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"];
                };
            };
        };
    };
    folioman_app_api_families_get_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDetailOut"];
                };
            };
        };
    };
    folioman_app_api_families_delete_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_families_update_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"];
                };
            };
        };
    };
    folioman_app_api_families_family_aggregate: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyAggregateOut"];
                };
            };
        };
    };
    folioman_app_api_families_family_valuation_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationStatusOut"];
                };
            };
        };
    };
    folioman_app_api_families_family_value_series_endpoint: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                granularity?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueSeriesOut"];
                };
            };
        };
    };
    folioman_app_api_imports_import_cas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Confirm
                     * @default false
                     */
                    confirm?: boolean;
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                    /**
                     * Password
                     * @default
                     */
                    password?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_imports_preview_cas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                    /**
                     * Password
                     * @default
                     */
                    password?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasPreviewOut"];
                };
            };
        };
    };
    folioman_app_api_investors_list_investors: {
        parameters: {
            query?: {
                family_id?: number | null;
                unaffiliated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"][];
                };
            };
        };
    };
    folioman_app_api_investors_create_investor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"];
                };
            };
        };
    };
    folioman_app_api_investors_roster_aggregate: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterAggregateOut"];
                };
            };
        };
    };
    folioman_app_api_investors_get_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorDetailOut"];
                };
            };
        };
    };
    folioman_app_api_investors_delete_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_investors_update_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"];
                };
            };
        };
    };
    folioman_app_api_exports_capital_gains: {
        parameters: {
            query: {
                fy: string;
                include_unreconciled?: boolean;
            };
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapitalGainsOut"];
                };
            };
        };
    };
    folioman_app_api_exports_export_holdings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_exports_schedule_112a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule112ARequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule112AResponse"];
                };
            };
        };
    };
    folioman_app_api_exports_export_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_investors_list_folios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolioOut"][];
                };
            };
        };
    };
    folioman_app_api_investors_scheme_detail: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                investor_id: number;
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeDetailOut"];
                };
            };
        };
    };
    folioman_app_api_imports_list_import_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"][];
                };
            };
        };
    };
    folioman_app_api_imports_import_csv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_imports_get_import_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_integrity_list_integrity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"][];
                };
            };
        };
    };
    folioman_app_api_integrity_recompute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"][];
                };
            };
        };
    };
    folioman_app_api_integrity_acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                security_id: number;
                folio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"];
                };
            };
        };
    };
    folioman_app_api_integrity_unacknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                security_id: number;
                folio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"];
                };
            };
        };
    };
    folioman_app_api_investors_investor_summary: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorSummaryOut"];
                };
            };
        };
    };
    folioman_app_api_investors_list_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
        };
    };
    folioman_app_api_investors_create_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
        };
    };
    folioman_app_api_investors_investor_valuation_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationStatusOut"];
                };
            };
        };
    };
    folioman_app_api_investors_investor_value_series: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                granularity?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueSeriesOut"];
                };
            };
        };
    };
    folioman_app_api_meta_app_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppMetaOut"];
                };
            };
        };
    };
}
