/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain Token
         * @description Exchange username + password for an access + refresh token pair.
         */
        post: operations["folioman_app_api_tokens_obtain_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Mint a fresh access token from a still-valid refresh token.
         */
        post: operations["folioman_app_api_tokens_refresh_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Families */
        get: operations["folioman_app_api_families_list_families"];
        put?: never;
        /** Create Family */
        post: operations["folioman_app_api_families_create_family"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Family */
        get: operations["folioman_app_api_families_get_family"];
        put?: never;
        post?: never;
        /** Delete Family */
        delete: operations["folioman_app_api_families_delete_family"];
        options?: never;
        head?: never;
        /** Update Family */
        patch: operations["folioman_app_api_families_update_family"];
        trace?: never;
    };
    "/api/families/{family_id}/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Family Aggregate */
        get: operations["folioman_app_api_families_family_aggregate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investors */
        get: operations["folioman_app_api_investors_list_investors"];
        put?: never;
        /** Create Investor */
        post: operations["folioman_app_api_investors_create_investor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investor */
        get: operations["folioman_app_api_investors_get_investor"];
        put?: never;
        post?: never;
        /** Delete Investor */
        delete: operations["folioman_app_api_investors_delete_investor"];
        options?: never;
        head?: never;
        /** Update Investor */
        patch: operations["folioman_app_api_investors_update_investor"];
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Holdings
         * @description Current holdings + valuation as a downloadable CSV (free tier).
         */
        get: operations["folioman_app_api_exports_export_holdings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/schedule-112a": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule 112A */
        post: operations["folioman_app_api_exports_schedule_112a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/exports/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Full transaction ledger as a CSV in the import format (round-trippable).
         */
        get: operations["folioman_app_api_exports_export_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/folios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folios */
        get: operations["folioman_app_api_investors_list_folios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Import Jobs */
        get: operations["folioman_app_api_imports_list_import_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports/cas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Cas
         * @description Import any CAS PDF — a CAMS/KFin MF CAS or an NSDL/CDSL eCAS.
         *
         *     The type is auto-detected: an MF CAS becomes a transaction ledger; an eCAS is
         *     the depository's authoritative snapshot (refreshes holdings). If applying an
         *     eCAS would *remove* securities, the job returns status ``needs_confirmation``
         *     with ``result.removals`` and persists nothing — resubmit with ``confirm=true``
         *     to apply. An eCAS older than the latest on file is rejected.
         */
        post: operations["folioman_app_api_imports_import_cas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv */
        post: operations["folioman_app_api_imports_import_csv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Job */
        get: operations["folioman_app_api_imports_get_import_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Integrity */
        get: operations["folioman_app_api_integrity_list_integrity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["folioman_app_api_integrity_recompute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/integrity/{security_id}/{folio_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["folioman_app_api_integrity_acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investor Summary
         * @description Roster headline numbers: current INR value, tax-ready vs total holdings,
         *     items needing attention, and the last successful import date.
         */
        get: operations["folioman_app_api_investors_investor_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{investor_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["folioman_app_api_investors_list_transactions"];
        put?: never;
        /**
         * Create Transaction
         * @description Manually add one transaction (security identified inline, upserted).
         */
        post: operations["folioman_app_api_investors_create_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessOut */
        AccessOut: {
            /** Access */
            access: string;
        };
        /** AssetMixRow */
        AssetMixRow: {
            /** Security Type */
            security_type: string;
            /** Value Inr */
            value_inr: string;
        };
        /** FamilyAggregateOut */
        FamilyAggregateOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Mix */
            asset_mix: components["schemas"]["AssetMixRow"][];
            /** Family Id */
            family_id: number;
            /** Investor Count */
            investor_count: number;
            /** Stale Count */
            stale_count: number;
            /** Top Holdings */
            top_holdings: components["schemas"]["HoldingValueRow"][];
            /** Total Inr */
            total_inr: string;
        };
        /** FamilyDetailOut */
        FamilyDetailOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Investor Count */
            investor_count: number;
            /** Investors */
            investors: components["schemas"]["InvestorOut"][];
            /** Name */
            name: string;
        };
        /** FamilyIn */
        FamilyIn: {
            /** Name */
            name: string;
        };
        /** FamilyOut */
        FamilyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Investor Count */
            investor_count: number;
            /** Name */
            name: string;
        };
        /** FolioOut */
        FolioOut: {
            /** Amc Code */
            amc_code: string;
            /** Broker */
            broker: string;
            /** Folio Type */
            folio_type: string;
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Pan Kyc */
            pan_kyc: boolean;
        };
        /** FolioRef */
        FolioRef: {
            /** Broker */
            broker: string;
            /** Folio Type */
            folio_type: string;
            /** Id */
            id: number;
            /** Number */
            number: string;
        };
        /** HoldingValueRow */
        HoldingValueRow: {
            /** Name */
            name: string;
            /** Security Id */
            security_id: number;
            /** Security Type */
            security_type: string;
            /** Units */
            units: string;
            /** Value Inr */
            value_inr: string | null;
        };
        /** ImportJobOut */
        ImportJobOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string;
            /** Filename */
            filename: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Investor Id */
            investor_id: number;
            /** Kind */
            kind: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Source Ref */
            source_ref: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** IntegrityStatusOut */
        IntegrityStatusOut: {
            folio: components["schemas"]["FolioRef"];
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
            /** Last Reconciled At */
            last_reconciled_at: string | null;
            security: components["schemas"]["SecurityRef"];
            /** Status */
            status: string;
            /** Tax Safe */
            tax_safe: boolean;
            /** Units From Holdings */
            units_from_holdings: string | null;
            /** Units From Transactions */
            units_from_transactions: string | null;
        };
        /** InvestorIn */
        InvestorIn: {
            /**
             * Email
             * @default
             */
            email: string;
            /** Family Id */
            family_id?: number | null;
            /**
             * Is Huf
             * @default false
             */
            is_huf: boolean;
            /** Name */
            name: string;
            /** Pan */
            pan?: string | null;
            /**
             * Relation
             * @default
             */
            relation: string;
        };
        /** InvestorOut */
        InvestorOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Family Id */
            family_id: number | null;
            /** Has Pan */
            has_pan: boolean;
            /** Id */
            id: number;
            /** Is Huf */
            is_huf: boolean;
            /** Name */
            name: string;
            /** Relation */
            relation: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InvestorSummaryOut
         * @description Per-investor headline numbers for the roster row.
         */
        InvestorSummaryOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Holdings Count */
            holdings_count: number;
            /** Investor Id */
            investor_id: number;
            /** Last Import At */
            last_import_at: string | null;
            /** Needs Attention Count */
            needs_attention_count: number;
            /** Snapshot Count */
            snapshot_count: number;
            /** Stale Count */
            stale_count: number;
            /** Tax Ready Count */
            tax_ready_count: number;
            /** Total Inr */
            total_inr: string;
        };
        /** InvestorUpdate */
        InvestorUpdate: {
            /** Email */
            email?: string | null;
            /** Family Id */
            family_id?: number | null;
            /** Is Huf */
            is_huf?: boolean | null;
            /** Name */
            name?: string | null;
            /** Pan */
            pan?: string | null;
            /** Relation */
            relation?: string | null;
        };
        /** Schedule112ARequest */
        Schedule112ARequest: {
            /**
             * Fy
             * @description India FY, e.g. 2024-25
             */
            fy: string;
            /**
             * Include Unreconciled
             * @default false
             */
            include_unreconciled: boolean;
        };
        /** Schedule112AResponse */
        Schedule112AResponse: {
            /** Columns */
            columns: string[];
            /** Fy */
            fy: string;
            /** Include Unreconciled */
            include_unreconciled: boolean;
            /** Row Count */
            row_count: number;
            /** Rows */
            rows: {
                [key: string]: string;
            }[];
        };
        /** SecurityRef */
        SecurityRef: {
            /** Id */
            id: number;
            /** Isin */
            isin: string;
            /** Name */
            name: string;
            /** Security Type */
            security_type: string;
            /** Symbol */
            symbol: string;
        };
        /** TokenObtainIn */
        TokenObtainIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /** TokenRefreshIn */
        TokenRefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /**
         * TransactionIn
         * @description A single manually-entered transaction (security identified inline).
         */
        TransactionIn: {
            /**
             * Amfi Code
             * @default
             */
            amfi_code: string;
            /** Amount */
            amount?: number | string | null;
            /**
             * Broker
             * @default
             */
            broker: string;
            /**
             * Brokerage
             * @default 0
             */
            brokerage: number | string;
            /**
             * Coin Id
             * @default
             */
            coin_id: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Fees
             * @default 0
             */
            fees: number | string;
            /** Folio Number */
            folio_number: string;
            /**
             * Isin
             * @default
             */
            isin: string;
            /** Name */
            name: string;
            /** Price */
            price: number | string;
            /**
             * Principal
             * @default
             */
            principal: string;
            /** Security Type */
            security_type: string;
            /**
             * Stamp Duty
             * @default 0
             */
            stamp_duty: number | string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Transaction Type */
            transaction_type: string;
            /** Units */
            units: number | string;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Amount */
            amount: string | null;
            /** Brokerage */
            brokerage: string;
            /** Currency */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fees */
            fees: string;
            /** Folio Id */
            folio_id: number | null;
            /** Id */
            id: number;
            /** Investor Id */
            investor_id: number;
            /** Nav Or Price */
            nav_or_price: string;
            /** Security Id */
            security_id: number;
            /** Source */
            source: string;
            /** Stamp Duty */
            stamp_duty: string;
            /** Transaction Type */
            transaction_type: string;
            /** Units */
            units: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    folioman_app_api_tokens_obtain_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
        };
    };
    folioman_app_api_tokens_refresh_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessOut"];
                };
            };
        };
    };
    folioman_app_api_families_list_families: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"][];
                };
            };
        };
    };
    folioman_app_api_families_create_family: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"];
                };
            };
        };
    };
    folioman_app_api_families_get_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyDetailOut"];
                };
            };
        };
    };
    folioman_app_api_families_delete_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_families_update_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"];
                };
            };
        };
    };
    folioman_app_api_families_family_aggregate: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyAggregateOut"];
                };
            };
        };
    };
    folioman_app_api_investors_list_investors: {
        parameters: {
            query?: {
                family_id?: number | null;
                unaffiliated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"][];
                };
            };
        };
    };
    folioman_app_api_investors_create_investor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"];
                };
            };
        };
    };
    folioman_app_api_investors_get_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"];
                };
            };
        };
    };
    folioman_app_api_investors_delete_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_investors_update_investor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorOut"];
                };
            };
        };
    };
    folioman_app_api_exports_export_holdings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_exports_schedule_112a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule112ARequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule112AResponse"];
                };
            };
        };
    };
    folioman_app_api_exports_export_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folioman_app_api_investors_list_folios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolioOut"][];
                };
            };
        };
    };
    folioman_app_api_imports_list_import_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"][];
                };
            };
        };
    };
    folioman_app_api_imports_import_cas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Confirm
                     * @default false
                     */
                    confirm?: boolean;
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                    /**
                     * Password
                     * @default
                     */
                    password?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_imports_import_csv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_imports_get_import_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
        };
    };
    folioman_app_api_integrity_list_integrity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"][];
                };
            };
        };
    };
    folioman_app_api_integrity_recompute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"][];
                };
            };
        };
    };
    folioman_app_api_integrity_acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                security_id: number;
                folio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatusOut"];
                };
            };
        };
    };
    folioman_app_api_investors_investor_summary: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorSummaryOut"];
                };
            };
        };
    };
    folioman_app_api_investors_list_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
        };
    };
    folioman_app_api_investors_create_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
        };
    };
}
