import { registerSW } from 'virtual:pwa-register'

import { setUpdater, updateAvailable } from './updateState'

// A long-open SPA tab never navigates, so it would never re-fetch sw.js and would
// miss new deploys until a manual hard refresh. Poll for a fresh worker this often
// — plus whenever the tab is refocused or connectivity returns — so the "new
// version" banner appears promptly without the user reloading.
const UPDATE_POLL_MS = 60 * 60 * 1000 // hourly

/**
 * Register the Workbox service worker generated by vite-plugin-pwa.
 *
 * `registerType: 'prompt'` (see vite.config.ts): a new shell is precached but NOT
 * applied silently — `onNeedRefresh` raises a banner (see UpdateBanner.vue) and the
 * user reloads when convenient, so a redeploy never reloads the page out from under
 * an edit in progress.
 */
export function registerServiceWorker(): void {
  const updateSW = registerSW({
    immediate: true,
    onNeedRefresh() {
      updateAvailable.value = true
    },
    onRegisteredSW(_swScriptUrl, registration) {
      if (!registration) return
      const check = () => {
        if (navigator.onLine) void registration.update().catch(() => {})
      }
      setInterval(check, UPDATE_POLL_MS)
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') check()
      })
      window.addEventListener('online', check)
    },
    onRegisterError(error) {
      console.error('[pwa] service worker registration failed', error)
    },
  })

  // The banner's "Reload": tell the waiting worker to skipWaiting, then reload once
  // it controls the page so the user lands on a fully fresh bundle.
  setUpdater(() => updateSW(true))

  // Safety net for contexts the SW doesn't cover (the desktop shell, dev) and for a
  // lazy chunk that 404s in the gap right after a deploy: reload once so a stale
  // dynamic import never dead-ends on a blank route. Guarded against a reload loop
  // if the chunk is genuinely gone (it then surfaces normally instead of thrashing).
  window.addEventListener('vite:preloadError', () => {
    const RELOADED_KEY = 'folioman.preloadReloaded'
    if (sessionStorage.getItem(RELOADED_KEY)) return
    sessionStorage.setItem(RELOADED_KEY, '1')
    window.location.reload()
  })
}
