import { registerSW } from 'virtual:pwa-register'

/**
 * Register the Workbox service worker generated by vite-plugin-pwa.
 *
 * `registerType: 'autoUpdate'` (see vite.config.ts) means a new shell is
 * applied automatically; we reload once the fresh SW takes control so the
 * user is never left on a half-updated bundle.
 */
export function registerServiceWorker(): void {
  registerSW({
    immediate: true,
    onRegisterError(error) {
      console.error('[pwa] service worker registration failed', error)
    },
  })
}
